spring:
  application:
    name: quest-analytics-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/quest_analytics_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    # Automatic database creation is handled by DatabaseInitializer
    # The database will be created automatically if it doesn't exist
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate will automatically create/update tables when the application starts

server:
  port: 8081

logging:
  level:
    com.questanalytics: INFO

